In [51]:
import pandas as pd
import numpy as np


In [52]:
print("Hello")

Hello


##Numpy

### varför numpy
- Numpy är skrivet i C
--Python är dynamiskt typad språk interperat språk --dvs otroligt långsamt
-- C är ett statiskt typat språk kompilerat språk  -dvs otroligt snabbt

Numpy arrayer kan endast ha en datatyp

In [53]:
lst = list([1,2,3,4,"Hej"])
print(lst)
arr = np.array(lst)
arr

arr = np.array([1,2,3,4],dtype=np.int8)
print(arr)
arr.dtype

[1, 2, 3, 4, 'Hej']
[1 2 3 4]


dtype('int8')

Det finns inbyggda funktioner för att skapa arrayer
De kan också vara och är oftast multidimensionella

In [54]:
ones_array = np.ones((9,3),dtype=np.int64)
print(ones_array)
print(ones_array.shape)
ones_array = ones_array.reshape((3,9))
ones_array

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(9, 3)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [55]:
range_array = np.arange(1,43).reshape(2,21)
print(range_array)
ones_array[0] = 0
ones_array[1] = 1
ones_array[2] = 2
# print (ones_array)
# print(ones_array[:2])
# print(ones_array[1:2])
# print(ones_array[:,:])
print(ones_array[1:,1:4])


[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]]
[[1 1 1]
 [2 2 2]]


Det finns inbyggda -metoder för att gör beräkningar på arrayer

In [56]:
print(range_array[0].prod())
print(range_array.max())
print(range_array.min())
print(range_array.sum(axis=1))
print(range_array.sum(axis=0))
print(range_array[0].cumprod())
range_array

-1195114496
42
1
[231 672]
[23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63]
[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42]])

Numpy har några inbyggda konstanter som vi kan nyttja,exempelvis

In [57]:
np.pi
np.nan
np.Infinity

inf

Vi kan iterera över en array

In [58]:
for thing in range_array:
    print(thing)

for thing in np.nditer(range_array):
    print(thing)

range_array[:,2] +=10

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42


##Pandas

### Varför pandas
-- Pandas är byggt på numpy och är skrivet i c ,dvs snabbt
-- Pandas är en dataanalysbibliotek,lätt att läsa in
-- Lätt att ha strukturerad data


I pandas jobbar vi med dataframes on series oftast

In [59]:
my_data_dict = {
    "person":["Anton","John","Sven","Pei","Lisa","Ann"],
    "age":[31,56,1,33,37,98]
}
df_from_dict = pd.DataFrame(my_data_dict)
df_from_dict

person  age
0  Anton   31
1   John   56
2   Sven    1
3    Pei   33
4   Lisa   37
5    Ann   98

In [60]:
df_from_dict.iloc[0]
df_from_dict.iloc[0]["person"]
df_from_dict["person"][:5]


0    Anton
1     John
2     Sven
3      Pei
4     Lisa
Name: person, dtype: object

In [61]:
people = df_from_dict["person"]
people.name
people.size
people.hasnans
people.value_counts()


Anton    1
John     1
Sven     1
Pei      1
Lisa     1
Ann      1
Name: person, dtype: int64

In [62]:
df = pd.read_csv("data.csvt")
df


dok_id   dok_rm  dok_nummer            dok_datum  \
0     HA091  2022/23           1  2022-09-26 00:00:00   
1     HA091  2022/23           1  2022-09-26 00:00:00   
2     HA091  2022/23           1  2022-09-26 00:00:00   
3     HA091  2022/23           1  2022-09-26 00:00:00   
4     HA091  2022/23           1  2022-09-26 00:00:00   
...     ...      ...         ...                  ...   
3891  HA099  2022/23           9  2022-10-17 00:00:00   
3892  HA099  2022/23           9  2022-10-17 00:00:00   
3893  HA099  2022/23           9  2022-10-17 00:00:00   
3894  HA099  2022/23           9  2022-10-17 00:00:00   
3895  HA099  2022/23           9  2022-10-17 00:00:00   

                                 avsnittsrubrik kammaraktivitet  \
0     Hälsningsanförande från ålderspresidenten             NaN   
1                     Val av förste vice talman             NaN   
2                     Val av förste vice talman             NaN   
3                      Val av andre vice talman             NaN   
4                      Val av andre vice talman             NaN   
...                                         ...             ...   
3891     Prövning av förslag till statsminister             NaN   
3892     Prövning av förslag till statsminister             NaN   
3893     Prövning av förslag till statsminister             NaN   
3894     Prövning av förslag till statsminister             NaN   
3895     Prövning av förslag till statsminister             NaN   

      anforande_nummer                talare parti  \
0                    1    Carina Ohlsson (S)     S   
1                   10  Gunilla Carlsson (S)     S   
2                   11        Annie Lööf (C)     C   
3                   12     Henrik Vinge (SD)    SD   
4                   13  Annika Hirvonen (MP)    MP   
...                ...                   ...   ...   
3891                 5       Per Bolund (MP)    MP   
3892                 6        Annie Lööf (C)     C   
3893                 7   Jimmie Åkesson (SD)    SD   
3894                 8       Ebba Busch (KD)    KD   
3895                 9  Nooshi Dadgostar (V)     V   

                                          anforandetext  intressent_id  \
0      Ärade riksdagsledamöter! Mina damer och herra...   8.599683e+11   
1      Fru ålderspresident! Jag vill å den socialdem...   8.752213e+11   
2      Fru ålderspresident och ärade ledamöter av Sv...   8.628683e+11   
3      Fru ålderspresident! Jag vill börja med att g...   4.068319e+11   
4      Fru ålderspresident! När vetskapen om Moderat...   8.196016e+11   
...                                                 ...            ...   
3891   Herr talman! Ärade ledamöter! Sverige är ett ...   9.564443e+11   
3892    STYLEREF Kantrubrik \* MERGEFORMAT Prövning ...   8.628683e+11   
3893   Herr talman! Det är inte vi här inne i riksda...   5.120752e+10   
3894    STYLEREF Kantrubrik \* MERGEFORMAT Prövning ...   5.125107e+11   
3895   Herr talman! Sverige kan vara på väg in i en ...   7.215098e+11   

     rel_dok_id replik  
0           NaN      N  
1           NaN      N  
2           NaN      N  
3           NaN      N  
4           NaN      N  
...         ...    ...  
3891        NaN      N  
3892        NaN      N  
3893        NaN      N  
3894        NaN      N  
3895        NaN      N  

[3896 rows x 13 columns]

In [ ]:
df.shape
filtered_df = df.filter(["talare", "parti", "dok_nummer"])
filtered_df["dok_nummer"].max()
filtered_df["dok_nummer"].min()
filtered_df["dok_nummer"].cumprod()
filtered_df["talare"].value_counts()
filtered_df = filtered_df.drop(["dok_nummer"], axis=1)
filtered_df = filtered_df.drop(0, axis=0)
filtered_df


In [63]:
import requests

res = requests.get("http://127.0.0.1:8000/todos")
if not res.status_code == 200:
    print("HTTP error bruh")

df_from_json_res = pd.read_json(res.text)
df_from_json_res


id     title                    description
0   1  Do  this  Dont do  that when doing this
1   3      dogs                        dogs---

In [64]:
df_from_json_file = pd.read_json("../lesson11/seed.json")
df_from_json_file


title  \
0                          Wake up   
1                      Wiggle toes   
2                      Find katana   
3  Decapitate japanese yakuza boss   
4                        Kill Bill   

                                         description  
0                                  Wake up from coma  
1          Find weird sexist truck to wiggle toes in  
2            I heard Hattori Hanzo is the guy to see  
3                 The katana will come in handy here  
4  Use the weird death punch i learned about, som...

Pandas kan också göra sql queries

In [69]:
import sqlite3
conn = sqlite3.connect("../lesson11/todo.db")
df_from_sql_query = pd.read_sql("SELECT * FROM todo",con=conn)
df_from_sql_query

id     title                    description
0   1  Do  this  Dont do  that when doing this
1   2     Do it             Greetings from yll
2   4   Do this             Greeting from Erik

Vi kan lägga till tabeller i en dataframe 

In [92]:
df = pd.read_csv("data.csvt")
filtered_df = df.filter(["talare","parti","anforandetext"])
text_lenght = pd.Series(name="text_lenght", data=[
                        len(row) for row in df["anforandetext"]])
text_lenght
filtered_df["text_lenght"] = text_lenght
filtered_df
df = pd.concat([df, filtered_df],axis=1)
df
filtered_df["text_lenght"].hasnans



False

In [81]:
filtered_df.to_csv("my_csv.csv")
filtered_df.to_json("my_csc.json")
filtered_df.to_html("my_html.html")
filtered_df


talare parti  \
0       Carina Ohlsson (S)     S   
1     Gunilla Carlsson (S)     S   
2           Annie Lööf (C)     C   
3        Henrik Vinge (SD)    SD   
4     Annika Hirvonen (MP)    MP   
...                    ...   ...   
3891       Per Bolund (MP)    MP   
3892        Annie Lööf (C)     C   
3893   Jimmie Åkesson (SD)    SD   
3894       Ebba Busch (KD)    KD   
3895  Nooshi Dadgostar (V)     V   

                                          anforandetext  text_length  
0      Ärade riksdagsledamöter! Mina damer och herra...         1162  
1      Fru ålderspresident! Jag vill å den socialdem...          724  
2      Fru ålderspresident och ärade ledamöter av Sv...          591  
3      Fru ålderspresident! Jag vill börja med att g...         2915  
4      Fru ålderspresident! När vetskapen om Moderat...         7226  
...                                                 ...          ...  
3891   Herr talman! Ärade ledamöter! Sverige är ett ...         8027  
3892    STYLEREF Kantrubrik \* MERGEFORMAT Prövning ...         5234  
3893   Herr talman! Det är inte vi här inne i riksda...         4713  
3894    STYLEREF Kantrubrik \* MERGEFORMAT Prövning ...         5645  
3895   Herr talman! Sverige kan vara på väg in i en ...        10388  

[3896 rows x 4 columns]

Vi kan plota från en dataframe,me då måste matplotlib installeras

In [95]:
plot = filtered_df[:5].plot(x="talare",y="text_lenght",kind="bar")
plot.figure.savefig("test.svg",format="svg")